export function nd_set_rest(notes, n) {
  notes[n].abc_note = 'z';
  notes[n].abc_alter = '';
  notes[n].startsTie = false;
  if (n) {
    notes[n - 1].startsTie = false;
  }
}

export function nd_append_measure(notesData) {
  for (let v=0; v<notesData.voices.length; ++v) {
    let vc = notesData.voices[v];
    vc.notes.push({abc_note: 'z', abc_alter: '', len: notesData.time.measure_len, startsTie: false});
  }
}

export let notesData = {
  key: {
    mode: 9, // 0 - major, 2 - dorian, 9 - aeolian
    fifths: 0, // Number of alterations near key
    base_note: 9, // Base tonic note (C - 0, Am - 9)
    maj_base_note: 0, // Base note if it was major (C - 0, Am - 0)
    base_note_alter: 0 // Alteration to achieve base tonic note
  },
  time: {
    beats_per_measure: 4,
    beat_type: 4,
    measure_len: 16
  },
  voices: [
    {
      clef: 'treble',
      name: 'Sop.',
      notes: [
        {abc_note: 'c', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'd', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'e', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'f', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'c', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'd', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'e', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'f', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'c', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'd', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'e', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'f', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'c', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'd', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'e', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'f', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'c', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'd', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'e', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'f', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'c', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'd', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'e', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'f', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'c', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'd', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'e', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'f', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'c', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'd', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'e', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'f', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'c', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'd', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'e', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'f', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'c', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'd', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'e', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'f', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'c', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'd', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'e', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'f', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'c', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'd', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'e', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'f', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'c', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'd', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'e', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'f', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'c', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'd', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'e', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'f', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'c', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'd', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'e', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'f', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'c', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'd', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'e', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'f', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'c', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'd', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'e', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'f', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'c', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'd', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'e', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'f', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'c', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'd', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'e', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'f', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'c', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'd', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'e', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'f', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'c', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'd', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'e', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'f', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'c', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'd', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'e', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'f', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'c', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'd', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'e', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'f', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'c', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'd', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'e', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'f', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'c', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'd', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'e', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'f', abc_alter: '', len: 4, startsTie: false},
      ]
    },
    {
      clef: 'treble',
      name: 'Alt.',
      notes: [
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 2, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 2, startsTie: true},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '^', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '_', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '=', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 2, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 2, startsTie: true},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '^', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '_', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '=', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 2, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 2, startsTie: true},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '^', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '_', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '=', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 2, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 2, startsTie: true},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '^', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '_', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '=', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 2, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 2, startsTie: true},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '^', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '_', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '=', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
      ]
    },
    {
      clef: 'treble-8',
      name: 'Ten.',
      notes: [
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'E', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'F', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'E', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'F', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'E', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'F', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'E', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'F', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'E', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'F', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'E', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'F', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'E', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'F', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'E', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'F', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'E', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'F', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'E', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'F', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'E', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'F', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'E', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'F', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'E', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'F', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'E', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'F', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'E', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'F', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'E', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'F', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'E', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'F', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'E', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'F', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'E', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'F', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'E', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'F', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'E', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'F', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'E', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'F', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'E', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'F', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'E', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'F', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'E', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'F', abc_alter: '', len: 4, startsTie: false},
      ]
    },
    {
      clef: 'bass',
      name: 'Bas.',
      notes: [
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 2, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 2, startsTie: true},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '^', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '_', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '=', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 2, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 2, startsTie: true},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '^', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '_', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '=', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 2, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 2, startsTie: true},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '^', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '_', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '=', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 2, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 2, startsTie: true},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '^', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '_', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '=', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 2, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 2, startsTie: true},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '^', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '_', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '=', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'D', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'C', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'B,', abc_alter: '', len: 4, startsTie: false},
        {abc_note: 'A,', abc_alter: '', len: 4, startsTie: false},
      ]
    }
  ],
  abc_charStarts: []
};
